name: Deploy iOS App to TestFlight
description: Composite action to deploy iOS app using Fastlane

inputs:

  appstore-key-id:
    required: true
    description: Key ID from App Store Connect API Key

  appstore-issuer-id:
    required: true
    description: Issuer ID from App Store Connect API Key

  appstore-private-key:
    required: true
    description: Base64-encoded contents of the .p8 private key file

  match-password:
    required: true
    description: Password used to encrypt/decrypt the certificates repository used by match

  match-git-basic-auth:
    required: true
    description: GitHub basic auth string (e.g., `https://<token>@github.com/...`) for accessing the match repo

runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Set up API key file
      run: |
        mkdir -p fastlane
        echo "${{ inputs.appstore-private-key }}" | base64 --decode > fastlane/Api_key.p8
      shell: bash

    - name: Run Fastlane beta lane
      env:
        APPSTORE_KEY_ID: ${{ inputs.appstore-key-id }}
        APPSTORE_ISSUER_ID: ${{ inputs.appstore-issuer-id }}
        MATCH_PASSWORD: ${{ inputs.match-password }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ inputs.match-git-basic-auth }}
      run: |
        bundle install
        bundle exec fastlane ios beta
      shell: bash