name: Deploy iOS App to TestFlight

on:
  workflow_call:
    inputs:
      ruby-version:
        required: false
        type: string
        default: '3.3.5'

      working-directory:
        required: true
        type: string

      scheme:
        required: true
        type: string

    secrets:
#      API_KEY_INFO:
#        required: true
      APPSTORE_KEY_ID:
        required: true
      APPSTORE_ISSUER_ID:
        required: true
      APPSTORE_PRIVATE_KEY:
        required: true
      MATCH_PASSWORD:
        required: true
      MATCH_GIT_BASIC_AUTHORIZATION:
        required: true

jobs:
  deployIos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true
          working-directory: ${{ inputs.working-directory }}

      - name: Set up API key file
        run: |
          mkdir -p "${{ inputs.working-directory }}/fastlane"
#          printf '%s' "${{ secrets.APPSTORE_PRIVATE_KEY }}" > "${{ inputs.working-directory }}/fastlane/Api_key.p8"
          echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" > ${{ inputs.working-directory }}/fastlane/Api_key.p8

      - name: Run Fastlane beta lane
        env:
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
#          APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          cd ${{ inputs.working-directory }}
          bundle exec fastlane ios beta

#          echo "${{ secrets.API_KEY_INFO }}" > ${{ inputs.working-directory }}/fastlane/api_key_info.json
#          printf '%s' "${{ secrets.API_KEY_INFO }}" > ${{ inputs.working-directory }}/fastlane/api_key_info.json

